import Head from 'next/head'
import { getDatabase } from '../utils/notion'
import Link from 'next/link'

export default function Home({ posts }: any) {
  console.log(posts)
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div>
          <h1>Welcome to my blog</h1>
          {posts.map((post: any) => {
            const date = new Date(post.created_time).toLocaleString('en-Us', {
              month: 'long',
              day: 'numeric',
              year: 'numeric'
            })
            return (
              <div key={post.id}>
                <span className="text-sm">{date}</span>
                <Link href="/[postId]" as={`/${post.id}`}>
                  Link
                </Link>
              </div>
            )
          })}
        </div>
      </main>
    </div>
  )
}

export const getStaticProps = async () => {
  const dbId: string = process.env.NOTION_DB_ID!
  const database = await getDatabase(dbId)

  return {
    props: {
      posts: database
    },
    revalidate: 1
  }
}
