import Head from 'next/head'
import Header from '../components/Header'

export default function Home() {
  return (
    <div style={{ width: '100%', height: '100vh' }}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
    </div>
  )
}
